#name: ecommerce-backend
#services:
#  adminer:
#    image: adminer
#    networks:
#      default: null
#    ports:
#    - mode: ingress
#      target: 8080
#      published: "8081"
#      protocol: tcp
#    restart: always
#  api:
#    build:
#      context: /Users/mathieuleprovost/Downloads/ecommerce-backend
#      dockerfile: Dockerfile
#    depends_on:
#      db:
#        condition: service_started
#        required: true
#    networks:
#      ecommerce-network: null
#    ports:
#    - mode: ingress
#      target: 8080
#      published: "5001"
#      protocol: tcp
#    restart: always
#  db:
#    environment:
#      MYSQL_DATABASE: e-commerce
#      MYSQL_ROOT_PASSWORD: e
#    image: mysql:8
#    networks:
#      ecommerce-network: null
#    restart: always
#networks:
#  default:
#    name: ecommerce-backend_default
#  ecommerce-network:
#    name: ecommerce-backend_ecommerce-network
